baseurl = "/"
languageCode = "en-us"
title = "Everest Law"
theme = "dimension"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<!--[-->SLOGAN GOES HERE<!--]-->'
  logo = "fa-balance-scale"
  copyright = "Everest Law"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[languages]
[languages.en]
languageName = "English"
weight = 1

[languages.de]
languageName = "Deutsch"
weight = 2
title = "Dimension"
  description = '<!--[-->SLOGAN GOES HERE<!--]-->'
  
